// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Ecdict is the predicate function for ecdict builders.
type Ecdict func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
